#!/usr/bin/env python3
import sys

def first(n, k):
    k *= 100
    i = 1
    while (i <= 100):
        print(str(i) + " " + str("%.2f" % n))
        n = (k / 100) * n * (1000 - n) / 1000
        i += 1

def second(n, i, iend):
    k = 100
    firsti = 1
    while(k <= 400):
        firsti = 1
        while (firsti < i):
            n = (k / 100) * n * (1000 - n) / 1000
            firsti += 1
        while (firsti <= iend):
            print(str("%.2f" % (k / 100)) + " " + str("%.2f" % n))
            n = (k / 100) * n * (1000 - n) / 1000
            firsti += 1
        k += 1



def usage():
    print('USAGE\n\t python3 main.py n [k | i0 i1]\n')
    print('DESCRIPTION\n\tn number of first generation individuals\n\tk growth rate from 1 to 4\n\ti0 initial generation (included)\n\ti1 final generation (included)')
    exit(0)

def error_handling():
    if (len(sys.argv) == 2):
        if (sys.argv[1] == '-h'):
            usage()
    if (len(sys.argv) <= 2 or len(sys.argv) > 4):
        exit(84)

def good_n():
    try :
        n = float(sys.argv[1])
    except ValueError:
        exit(84)
    if (n < 0):
        exit(84)
    return (n)

def good_k():
    try :
        k = float(sys.argv[2])
    except ValueError:
        exit(84)
    if (k < 1 or k > 4):
        exit(84)
    return (k)


def main():
    error_handling()
    n = good_n()
    if (len(sys.argv) == 3):
        k = good_k()
        first(n, k)
    if (len(sys.argv) == 4):
        try :
            i = int(sys.argv[2])
            iend = int(sys.argv[3])
        except ValueError:
            exit(84)
        if (iend < i):
            exit(84)
        second(n, i, iend)



if __name__ == "__main__":
    main()